### ISSUE TITLE
Linux Build - No text displayed

### ISSUE THREAD

**Issue by crshrprt** [reillypascal/RSBrokenMedia#2]
Thank you for this interesting plugin.

When building on Linux I get no text displayed in the GUI. 
I tried commenting, in `PluginEditor.cpp` and `GUIStyles.h`, where the font is set, compiled the plugin again and text is displayed.
I guess the problem occurs if the Verdana font is not found.

**Comment by reillypascal** [comment]
Thanks for letting me know! I will see what I can do about this.

**Comment by reillypascal** [comment]
I removed the Verdana font for now, so it should compile on Linux
